Add conditions to task list
liteflow-labs/service-database pull request #8
Opened 2020-08-21 11:08 UTC by NicolasMahe

based on https://github.com/liteflow-labs/service-database/pull/7 and https://github.com/liteflow-labs/service-database/pull/9

Add conditions to task list:

```yml
  list:
    description: List all data in a collection.
    inputs:
      collection: *inputCollection
      conditions:
        description: Conditions to apply when listing the documents. Only documents matching all the conditions will be returned.
        type: Object
        repeated: true
        optional: true
        object:
          path: { type: String }
          predicate: { type: String }
          value: { type: Any }
```

I choose to use a simplified version compared to the process node filter implementation in the backend. I try to implement something as close as possible as the [doc](https://docs.liteflow.com/references/filter.html). But I couldn't use the parameter `key` because of the compiler (so I added to the database pre-process a conversion, see PR: https://github.com/liteflow-labs/liteflow-js/pull/221).

Current limitation:
- Only one key in the path
- Only predicate `Eq`

2020-08-24 09:40 UTC, antho1404 requested changes

2020-08-24 09:40 UTC, antho1404 commented on src/tasks/list.ts
> +        },
This request might be really risky as we can inject SQL with our path. We should use query parameters more.
Something like that should work and fix some issues

```suggestion
        `document.value ->> :attr ${predicateToSql(condition.predicate)} :value${i}`,
        {
          attr: condition.path
          [`value${i}`]: condition.value,
        },
```

2020-08-25 08:17 UTC, NicolasMahe commented on src/tasks/list.ts
> +        },
done in https://github.com/liteflow-labs/service-database/pull/8/commits/25208d44dbb74903d169fa944218dae068c5f045

2020-08-25 08:18 UTC, antho1404 approved these changes

2020-08-25 08:18 UTC, merged